### ISSUE TITLE
Dokku Timeout :5000 Error

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-planninglabs-home#5]
The deployed app does not allow refreshing or directly loading some pages. Upon refresh or arrival, the app times out and redirects to `https://planninglabs.nyc:5000/[route]`.

**Comment by chriswhong** [comment]
Turns out you need to add a trailing slash to all links in a gatsby.js site.  Fixed in 5f4b679805be8e18566a1bfaa3956a284335a5c5

**Comment by chriswhong** [comment]
Turns out the above fix did not address the issue.  While it make sure that all internal links will load, and reload successfully, navigating directly to a subroute without a trailing slash still has problems.

I was able to locate https://github.com/ineffyble/buildpack-nginx/, which is a fork of the dokku nginx buildpack that includes the nginx configuration `port_in_redirect off;` which is meant to address this very issue.  There is an [open PR](https://github.com/dokku/buildpack-nginx/pull/21) on `dokku/buildpack-nginx`

I attempted to use the forked buildpack but wasn't able to get it working.  However, manually adding `port_in_redirect off;` inside the https `server` block in `/home/dokku/{appname}/dokku.conf` on the host machine seems to have done the trick.  

I am pretty sure we will need to manually add this again if the dokku configuration for this app ever changes, so we should leave this issue open as we're still searching for a non-hacky fix.

**Comment by chriswhong** [comment]
After some more messing about with this, it turns out we need to add `port_on_redirect off;` to _both_ nginx configs:

1) The container nginx config, which can be customized by adding `app-nginx.cong.sigil` to the root of the deployed repo.

2) The dokku app's nginx config (which runs on the dokku host), which can be customized by adding `nginx.conf.sigil` to the root of the deployed repo.

With both of these in place accessing https://planninglabs.nyc/about or any subroute without trailing  slash will redirect properly to add the trailing slash.

The addition of these two custom configs, plus modifications to the deploy script were added in 9cd0b8ae8f77d65fb119f7ff0253c5dc9855cd79 

Furthermore, the `gatsby-browser.js` customization to not require trailing slashes is not required.
